### PR TITLE
Minor spelling

### PR DESCRIPTION
**Pull request by lewisc64**

### CODE REVIEW

**Comment by lewisc64** [comment]
Not entirely sure whether you find this irritating or helpful.

**Comment by roryclaasen** [comment]
both

**Comment by lewisc64** [comment]
Well, it could be worse. I Could be creating pull requests for tiny changes. Oh wait...

**Comment by roryclaasen** [comment]
Remember if you want to check all my spelling you also need to check this branch [gh-pages](https://github.com/GOGO98901/RorysMod/tree/gh-pages).
The two files [index.html](https://github.com/GOGO98901/RorysMod/blob/gh-pages/index.html) and [module.html](https://github.com/GOGO98901/RorysMod/blob/gh-pages/module.html)

**Pull request merged**
